service: rimak

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x


  iamRoleStatements:
    - Effect: Allow
      Action:
        - comprehend:*
      Resource: "*"
functions:
  sentimentAnalisys:
    handler: handler.sentimentAnalisys
    events:
      - http: 
          method: post
          path: sentiment

