service: rimak

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  environment:
    MONGODB_DBNAME: ${ssm:/RIMAK/MONGODB_DBNAME}
    MONGO_URI: ${ssm:/RIMAK/MONGO_URI}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
        - ssm:GetParametersByPath
      Resource: "*"
    - Effect: Allow
      Action:
        - comprehend:*
      Resource: "*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: "arn:aws:lambda:us-east-1:*:*"
plugins:
  - serverless-offline
functions:
  feedback:
    handler: handler.webhookBot
    events:
      - http:
          path: webhook
          method: post
  sentimentAnalisys:
    handler: handler.sentimentAnalisys
    events:
      - http: 
          method: post
          path: sentiment
  processInsights:
    handler: processInsights.handler
  getInsights:
    handler: getInsights.handler
    timeout: 30
    events:
      - http:
          path: /insights
          method: post
          cors: true
